backend:
  name: github
  repo: stacksmithstudio/stacksmithstudio-site
  branch: master
  base_url: https://github.stacksmithstudio.com


media_folder: frontend/static/img
public_folder: frontend/img

collections:
  - name: "pages"
    label: "Pages"
    folder: "frontend/src/content/pages"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Categories", name: "categories", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "parts"
    label: "Parts"
    folder: "frontend/src/content/parts"
    create: false
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "posts"
    label: "Posts"
    folder: "frontend/src/content/posts"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Sub Title", name: "subTitle", widget: "string"}
      - {label: "Categories", name: "categories", widget: "list"}
      - {label: "Cover", name: "cover", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "projects"
    label: "Projects"
    folder: "frontend/src/content/projects"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Role", name: "role", widget: "string"}
      - {label: "Categories", name: "categories", widget: "list"}
      - {label: "Cover", name: "cover", widget: image}
      - {label: "Images", name: "images", widget: list, fields: [{label: "Image", name: "image", widget: image}]}
      - {label: "Job Type", name: "jobType", widget: "list"}
      - {label: "Featured?", name: "featured", widget: "boolean", default: true}
      - {label: "On Resume?", name: "resume", widget: "boolean", default: false}
      - {label: "Start Time", name: "startTime", widget: "date", format: "MMM YYYY"}
      - {label: "End Time", name: "endTime", widget: "date", format: "MMM YYYY"}
      - {label: "End Date", name: "endDate", widget: "date"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "proposals"
    label: "Proposals"
    folder: "frontend/src/content/proposals"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Images", name: "images", widget: list, fields: [{label: "Image", name: "image", widget: image}]}
      - {label: "Body", name: "body", widget: "markdown"}
